server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:littlefool6/cloud2021_config.git #GitHub上面的git仓库名字
          uri: https://github.com/littlefool6/cloud2021_config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - cloud2021_config
          force-pull: true
          username: littlefool6
          password: 5132977Abc???
      ####读取分支
      label: main

#rabbitmq相关配置
rabbitmq:
  host: 192.168.56.100
  port: 5672
  username: guest
  password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'